### ISSUE TITLE
Provide links to relevant MDN articles in comments

### ISSUE THREAD

**Issue by openjck** [mdn/YouShouldUse#15]

**Comment by openjck** [comment]
I would be interested in observing users before committing to this feature. I suspect the current warning messages will be sufficient in almost all cases. I don't see a need for detailed documentation about *usage* when we are only flagging property *compatibility*.

**Comment by groovecoder** [comment]
Somewhat related to https://github.com/mdn/YouShouldUse/issues/48 ...

If YouShouldUse is built on the [Fogg Behavior](http://www.behaviormodel.org/) and [Hooked](http://www.neurosciencemarketing.com/blog/articles/hooked-by-nir-eyal.htm) models with an emphasis on triggers/notification that flow into action, reward, and investment, then we should watch how users respond to a full cylce of that.

Without this or https://github.com/mdn/YouShouldUse/issues/15, the commit comment does not lead towards any particular action. I'd be happy to watch what users do with the commit comment, but the reality is that we simply can't, unless we're physically sitting behind them?

If we provide links back to MDN, complete with acquisition parameters, we can see how users use (or don't use) the actions we build into our triggers.

**Comment by openjck** [comment]
I agree that we need to see users acting on compatibility comments. Discord can't achieve its goals if people ignore it.

I disagree that compatibility comments don't lead to any particular actions. If something as simple as a phone buzzing can inspire someone to check their messages, even without a specific call-to-action to that effect, it seems reasonable that documentation about browser support would be enough to inspire someone to change their code.

**Comment by groovecoder** [comment]
Back to this since https://github.com/mdn/discord/issues/15 is closed.

We should measure CSS fixed directly then. That's how we'll watch users to determine if we're changing behavior or not.

In theory, we should be able to do this with the tool itself? Though we would have to start recording the # of issues found in each PR, which means we have to start storing results somewhere.

**Comment by openjck** [comment]
Definitely, it woulds like a database is in our future.

I think measuring corrections would be great! :smile:

**Comment by groovecoder** [comment]
Based on my experience with [the discord comment on MDN Tabzilla PR](https://github.com/mozilla/kuma/pull/3373#discussion-diff-35720306) we should re-consider this. A link to [MDN CSS media queries Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Media_queries?redirectlocale=en-US&redirectslug=CSS%2FMedia_queries#Browser_compatibility) could have done the same thing [that @alexgibson did](https://github.com/mozilla/tabzilla/issues/62) - i.e., explain that Safari would use the `device-pixel-ratio`.

**Comment by openjck** [comment]
Yeah, we should keep considering it. We definitely want to address needs that arise in the real world.

I would love to help us study users over time to understand how common the need is. We should be able to get an even clearer picture once we have more users and users with different backgrounds.

Somewhere there's a sweet spot between scope and maintainability. I would love to help us puzzle out its location so that we can have the best of both worlds.
