### ISSUE TITLE
Comment as MDN

### ISSUE THREAD

**Issue by groovecoder** [mdn/YouShouldUse#30]
**Current specification**

Compatibility comments should be made under the MDN brand. It should look like MDN itself added the comment.

![Comment to a line of code on GitHub. The comment is published by a user named "MDN" who is using the MDN logo as an avatar.](https://cloud.githubusercontent.com/assets/933396/7969678/99fe9760-0a06-11e5-81f1-79fe3fcbad66.png)

**Comment by mrmakeit** [comment]
The MDN organization cannot make API comments, so we will need to create a separate account for use with the hook.  Currently the FreeHooks GitHub account is attached to the master app, and openjdk is just used when he tests.

**Comment by openjck** [comment]
Updated the description an provided a demo screenshot.

**Comment by mrmakeit** [comment]
If one were able to acquire an MDN OAUTH token from GitHub, I could test it. But my last attempt to use an organization token lead to several features being unavailable.

**Comment by groovecoder** [comment]
FWIW, I'm going thru a process to register an "MDN Services Bot" user on GitHub for this.

**Comment by mrmakeit** [comment]
That works.  Just switch out the Heroku OAUTH_TOKEN variable when you are done.

**Comment by groovecoder** [comment]
I created https://github.com/mdn-services, an oauth token with notifications, public_repo, repo:status permissions, and set the heroku app OAUTH_TOKEN variable to use it.

**Comment by openjck** [comment]
Awesome. Can this be marked as closed, or is more needed for comments to start showing up under this account?

I notice the profile image looks distorted, especially around the edges. Maybe [this sharper image](https://developer.mozilla.org/media/img/opengraph-logo.png) would work better?

**Comment by groovecoder** [comment]
Updated the profile image. I'm not marking it closed because I can't get the webhook to work anymore. :cry: Still waiting for it to comment on https://github.com/groovecoder/sherwoodcourt.com/commit/28485239addcc05eed43411a97288f7f603c28b4.

**Comment by groovecoder** [comment]
Fixed. See https://github.com/openjck/YouShouldUse-test/commit/d39cc8ca63e3a1acfc40bd5e79c065a01659c882

**Comment by openjck** [comment]
Beautiful!
