### ISSUE TITLE
Record which repos are using the webhook

### ISSUE THREAD

**Issue by groovecoder** [mdn/YouShouldUse#33]

**Comment by mrmakeit** [comment]
Going to use this issue as an excuse to properly learn postgres

**Comment by groovecoder** [comment]
Don't let postgres turn into a yak-hole though. We can look for something easier if we want.

**Comment by mrmakeit** [comment]
In case it starts to, what alternatives would you suggest?

**Comment by groovecoder** [comment]
Even finding a way to use Heroku logs would work for me. Or adding New Relic, or anything really. Surely something in https://addons.heroku.com/?q=analytics or https://addons.heroku.com/?q=metrics should work. :smile:

**Comment by mrmakeit** [comment]
Don't we already log the payload?  That would have the repo name in it.

**Comment by groovecoder** [comment]
Log it where? :smile: I'm happy to close this if I can already see the payloads/repos somewhere.

**Comment by mrmakeit** [comment]
my bad. it got removed in the great console.log purge of #25
I'll add it back.

**Comment by openjck** [comment]
Fixed with #39.

**Comment by openjck** [comment]
My mistake. We have #40 open for restoring this.

**Comment by openjck** [comment]
We still need to add persistent logs. I can look into that tomorrow.

**Comment by mrmakeit** [comment]
I believe we are using something like papertrail, which just uses heroku's logs to save them.

**Comment by mrmakeit** [comment]
Refer to @groovecoder's last comment on #40 for more details.

**Comment by openjck** [comment]
I added the "Flixa" Papertrail plan. That gives us 50MB of logging per day, 365 days of logs, and searching up to 7 days in the past. The more expensive plans just increase the data cap; the other values remain the same.

Flixa for Blixa!
