### ISSUE TITLE
Add Severity Levels To Warnings

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/YouShouldUse#34]
It's be nice not to moderate the tone of the comments when a user is using good progressive enhancement techniques. For example: a box-radius that isn't supported is probably not going to be a problem but lack of support for display: flex could be pretty catastrophic.

**Comment by stephaniehobson** [comment]
Totally an enhancement not a high priority ;)

**Comment by mrmakeit** [comment]
That's a thought.  Is there a list of features that could be used, or are we going to have to update it ourselves.

**Comment by stephaniehobson** [comment]
Probably have to come up with and maintain the list ourselves :/

**Comment by stephaniehobson** [comment]
Or maybe we can talk Anand into integrating it into his project? The other feature I really want is probably going to have to come from him

**Comment by openjck** [comment]
Agreed. I think we should call this upstream. Let's continue the discussion in anandthakker/doiuse#13.
