### ISSUE TITLE
Check compatibility in Stylus stylesheets

### ISSUE THREAD

**Issue by jgmize** [mdn/YouShouldUse#36]
https://learnboost.github.io/stylus/

**Comment by groovecoder** [comment]
This is the one most interesting to me for MDN's own use. But what does it look like? Do we compile `.styl` files and then report incompatibilities in the resulting CSS on a commit?

**Comment by jgmize** [comment]
Compile with source map enabled, run analysis, use source map to comment on appropriate line in original commit.

**Comment by mrmakeit** [comment]
fixed in #42
