### ISSUE TITLE
Invalid Comment count

### ISSUE THREAD

**Issue by darkwing** [mdn/YouShouldUse#50]
After connecting the main YSU to my test repo, I saw this:

http://content.screencast.com/users/davidwalsh83/folders/Jing/media/052c27b5-cc74-4d09-a4e0-e35236172d05/00000293.png

"8 comments...."

Only one comment, however, was added:

https://github.com/darkwing/compat-tables/commit/3ccdf9437113a184e460fb6161975d1ea82cc6a9

**Comment by openjck** [comment]
We've seen this too. Something on our end might be triggering an unrelated bug in GitHub. I'm not sure they would ever want to show discrepant comment counts.

**Comment by mrmakeit** [comment]
how interesting.  I'm getting the same issue on unrelated repos as well.  I'm guessing it's GH.

**Comment by groovecoder** [comment]
Should open a support request with GitHub ...

**Comment by darkwing** [comment]
Oddly enough, I made a commit to remove my test file (https://github.com/darkwing/YouShouldUseTest):

https://github.com/darkwing/YouShouldUseTest/commit/2b33ebbfe2b4ab8f32d8e797aee1e730642a5622

... and GitHub still shows "1 comment"

![Image](http://content.screencast.com/users/davidwalsh83/folders/Jing/media/54ecce9c-1362-40cb-8172-4d6878341fea/00000298.png)

... but no comments display in the "Files" diff.  Weird.

**Comment by groovecoder** [comment]
Was this using the prod webhook at youshoulduse.herokuapp.com, or using your own webhook?

**Comment by darkwing** [comment]
My own

**Comment by darkwing** [comment]
Yeah, it's becoming painfully apparent that the comment count is a total for the given file(s), not the single commit  :/

**Comment by groovecoder** [comment]
File a bug for that?

**Comment by darkwing** [comment]
I will once I have more info, just thinking out loud here :/

**Comment by darkwing** [comment]
For my own reference:  http://stackoverflow.com/questions/18138885/github-api-v3-fetch-diff-of-specific-commit

**Comment by darkwing** [comment]
Closing for a more concise bug.
